version: 2
jobs:
  build:
    docker:
      - image: trussworks/circleci-docker-primary:279c3125f85d07bef8fe50d5adf9ee86bbfa27bd
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache
